### ISSUE TITLE
vite: "The package may have incorrect main/module/exports specified in its package.json."

### ISSUE THREAD

**Issue by wighawag** [drand/tlock-js#37]
tlock-js is incompatible with [vite](https://vitejs.dev/) and I suspect the error message from vite is correct and tlock-js must not follow modern export convention

Repro : https://github.com/wighawag/vite-tlock-js

```
pnpm i
pnpm dev
```

then navigate to the page and see error in console

```
Failed to resolve entry for package "tlock-js". The package may have incorrect main/module/exports specified in its package.json.
18:11:22 [vite] Internal server error: Failed to resolve entry for package "tlock-js". The package may have incorrect main/module/exports specified in its package.json.
  Plugin: vite:import-analysis
  File: /home/wighawag/dev/github.com/bug-reproduction/vite-tlock-js/src/tlock.ts
      at packageEntryFailure (file:///home/wighawag/dev/github.com/bug-reproduction/vite-tlock-js/node_modules/.pnpm/vite@4.3.9/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23382:11)
      at resolvePackageEntry (file:///home/wighawag/dev/github.com/bug-reproduction/vite-tlock-js/node_modules/.pnpm/vite@4.3.9/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23379:5)
      at tryNodeResolve (file:///home/wighawag/dev/github.com/bug-reproduction/vite-tlock-js/node_modules/.pnpm/vite@4.3.9/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:23113:20)
      at Context.resolveId (file:///home/wighawag/dev/github.com/bug-reproduction/vite-tlock-js/node_modules/.pnpm/vite@4.3.9/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:22874:28)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Object.resolveId (file:///home/wighawag/dev/github.com/bug-reproduction/vite-tlock-js/node_modules/.pnpm/vite@4.3.9/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:42847:32)
      at async TransformContext.resolve (file:///home/wighawag/dev/github.com/bug-reproduction/vite-tlock-js/node_modules/.pnpm/vite@4.3.9/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:42575:23)
      at async normalizeUrl (file:///home/wighawag/dev/github.com/bug-reproduction/vite-tlock-js/node_modules/.pnpm/vite@4.3.9/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:40500:34)
      at async file:///home/wighawag/dev/github.com/bug-reproduction/vite-tlock-js/node_modules/.pnpm/vite@4.3.9/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:40651:47
      at async Promise.all (index 0)
```

**Comment by wighawag** [comment]
looking deeper the npm packag's package.json has `"module": "module.js",` but the file `module.js` does not actually exists

**Comment by wighawag** [comment]
re buffer, 

after removing the line `"module": "module.js"` from `node_modules/tlock-js/package.json`

I can make it work by adding

```
import {Buffer} from 'buffer';
(globalThis as any).Buffer = Buffer
```

**Comment by CluEleSsUK** [comment]
Thanks for this find! I will remove the `module.js` from the package.json - it was a carryover from a previous build format that I forgot to nuke.

The `Buffer` thing is a bit of a pain and I've noticed it also when building on other projects. If I remember correctly, using just a `UInt8Array` was a bit of a pain without the convenience methods of `Buffer`, but I'll have a look to see if I can work around it

**Comment by CluEleSsUK** [comment]
Okay I think the issue with Buffer is actually easily solved - we include a dependency for `Buffer` and export it in `index.ts`... but the code itself uses the builtin node.js buffer and not the dependency -.-' will add imports where necessary!

**Comment by CluEleSsUK** [comment]
Please see the changes I've made here: https://github.com/drand/tlock-js/pull/38

I tested locally without setting `Buffer` in the global scope and it seems to work!
I tried migrating to `esbuild` instead of just tsc, but unfortunately all projects relying on `tlock-js/some-package` imports would be broken so abandoned such a plan

**Comment by wighawag** [comment]
it works

Thanks @CluEleSsUK !

**Comment by CluEleSsUK** [comment]
Ah, quite correct! Have added it here: https://github.com/drand/drand-client/pull/67
